### ISSUE TITLE
Store config somewhere

### ISSUE THREAD

**Issue by pas256** [cloudnative/lambda-chat#8]
We have a little config issue - it needs to be stored somewhere so it can be ready by

 - the website
 - the setup scripts
 - the lambda functions

Config are things like

 - the region
 - the S3 bucket and key
 - the DyanmoDB table name
 - the SNS name or ARN

Ideas?

**Comment by pas256** [comment]
Even more, if someone wants to fork this, they should be able to do so, modify the config, get it working in their AWS account, and then come back here and submit a PR without reveting their config file. This means something along the lines of having an example file in here, and the actual one which is listed in `.gitignore`

**Comment by garnaat** [comment]
Yeah, I think an example config in the repo and documentation about how to use it.

**Comment by pas256** [comment]
All config is going to be in `config.yml`.

I believe the file can be generated by the resources script by getting the Output from the CF stack

**Comment by pas256** [comment]
This seems to be working well
